### ISSUE TITLE
LS: Renommage de propriétés avec préfixe ou suffixe

### ISSUE THREAD

**Issue by gideruette** [klee-contrib/topmodel#10]
A faire après #9

**Comment by JabX** [comment]
#50 implémente la fonctionnalité sur les classes, reste les domaines et les propriétés.

**Comment by JabX** [comment]
#121 implémente le rename sur les domaines et les décorateurs

**Comment by JabX** [comment]
#185 implémente le renommage de propriétés, tant qu'il n'y a pas de préfixes/suffixes dans les références

**Comment by sebez** [comment]
Il faut gérer par exemple ce cas là : 

```yaml
---
class:
  name: Equipe
  comment: Equipe projet
  properties:
    - association: Utilisateur
      role: Leaddev
      comment: Lead dev.
    - association: Utilisateur
      role: Cheffe
      comment: Cheffe.

---
class:
  name: SousEquipe
  comment: Sous partie d'une équipe
  properties:
    - alias:
        class: Equipe
        include:
          - UtilisateurIdLeaddev
          - UtilisateurIdCheffe
```

Le renommage de la classe Utilisateur doit renommer la propriété UtilisateurIdLeaddev.

# Constaté

Le renommage de Utilisateur est autorisé mais ne renomme pas UtilisateurIdLeaddev.

# Correction

Dans RenameHandler, la méthode modelStore.GetReferencesForPositionInFile ne semble pas renvoyer les cas comme UtilisateurIdLeaddev.
