### ISSUE TITLE
Définition et génération de mappers

### ISSUE THREAD

**Issue by JabX** [klee-contrib/topmodel#102]
Sur une classe (`LeDto` dans l'exemple), on pourrait faire 

```yaml
mappers:
    to: 
      # Génère une méthode "ToClass1(dto: LeDto): Class1"
      - class: Class1
        name: Class1
        mappings:
          # Si on a plusieurs alias de "Id" de "Class1", Topmodel dirait un truc genre "plusieurs propriétés possibles pour "Id". Donc on dit celui qu'on veut
          Class1Id: Id
          # La aussi, mais au lieu de résoudre l'ambiguité on dis juste de l'ignore
          TypeTrucCode: false
      # Génère une méthode "ToClass2(dto: LeDto): Class2"
      - class: Class2
        name: Class2
    from:
      # Génère un constructeur
      - params:
          - class: Class1
            name: Class1
            mappings:
               Id: Class1Id
          - class: Class2
            name: Class2
```

ça marcherait par défaut avec des alias, et on pourrait ajouter des mappings en plus entre propriétés si elles ont le même domaine. comme pour les alias, on ne peut pas le faire avec des compositions.
