### ISSUE TITLE
Core: Ajouter la possibilité de customiser le nom et le préfix des endpoints

### ISSUE THREAD

**Issue by gideruette** [klee-contrib/topmodel#123]
Pour remplacer la notion de controller, cela pourrait ressembler à :

```yaml
endpoints:
  fileName: Demande
  prefix: Demande
```
