### ISSUE TITLE
Paramétrer la génération selon les tags de fichiers de modèles

### ISSUE THREAD

**Issue by gideruette** [klee-contrib/topmodel#138]
Pour pouvoir dépendre des classes générées dans les autres générateurs, et les référencer grâce à leur config

**Comment by JabX** [comment]
Il faut encore implémenter la génération selon le tag pour les APIs client/serveur (et les chemins de génération pour les modèles, clients et contrôleurs) dans les générateurs C# et Java.

**Comment by JabX** [comment]
La solution implémentée en JS avec `{tag}` dans le chemin de fichier est trop limitée pour les besoins des générateurs C# et Java. La configuration ressemblerait probablement à quelque chose comme

```yaml
tags:
    - Tag1
    - Tag2
    - Tag3
apiGeneration:
    Tag1: Client
    Tag2: Server
    Tag3: Server
modelRootPath:
    Tag1: App.{module}.Clients/Model
    Tag2: App.{module}.Models
    Tag3: App.{module}.Models
```
Les paramètres qui peuvent dépendre du tag pourront spécifier un mapping "tag => valeur" à la place de juste la valeur. L'ensemble des tags du générateur devront toujours être renseigné dans le mapping, sinon c'est une erreur de configuration. Cela impliquera probablement un léger retravail de l'usage des tags pour se servir de cette fonctionnalité.
