### ISSUE TITLE
Mappings sur les compositions

### ISSUE THREAD

**Issue by JabX** [klee-contrib/topmodel#146]
On voudrait gérer des cas simples et utiles comme : 

```yaml
# On suppose Classe1 et Classe2 classes persistées, Classe1 a une association vers Classe2, 
# avec Classe1DTO qui a une composition vers Classe2DTO via la propriété Classe2
# Tous les mappers sont sur Classe1DTO

from:
   - params:
      - class: Classe1
      - class: Classe2
        mappings:
           Classe2: this # Affecter un paramètre entier dans une composition. 
           # Autorisé si c'est le même type ou qu'il y a un mapper (from ou to)

# Les mappings association <> composition doivent être au choix : 
#  - "manyToOne/oneToOne" <> "object"
#  - "oneToMany/manyToMany" <> "list"

# Il faudra aussi que Classe2DTO ait une PK (via un alias à priori) de même domaine que Classe2Id
# Le générateur JPA aura une erreur supplémentaire si les types ne sont pas les mêmes et qu'il n'y a pas de mappers entre Class2 et Class2DTO

from:
  - params:
      - class: Classe1
        mappings:
            Classe2: Classe2Id # Crée une nouvelle instance de Classe2DTO avec l'id de Classe2. (C#)
                               # Mappe Classe2 vers Classe2DTO pour le mettre dans Classe2 (JPA)
to:
   - class: Classe1
     mappings:
       Classe2: Classe2Id # Récupère l'ID de Classe2DTO pour le mettre dans Classe2Id (C#)
                          # Mappe Classe2DTO vers Classe2 pour le mettre dans Classe2Id (JPA)
```
(Remarque : les compositions ne seront acceptées que sur la classe qui définit les mappers, donc à "gauche du mapping", ce qui met naturellement hors périmètre tout mapping composition <> composition)
