### ISSUE TITLE
Pouvoir générer des enums avec des associations ManyToOne ou OneToOne

### ISSUE THREAD

**Issue by Jerom138** [klee-contrib/topmodel#152]
Exemple : 
```
class:
  name: Rights
  comment: Table Rights
  reference: true
  decorators:
    - Builder
  properties:
    - name: Code
      comment: Code
      domain: DO_CODE_35
      label: Code
      primaryKey: true
    - name: Label
      comment: Label
      domain: DO_LIBELLE_LONG
      label: Label
    - association: RightCategory
      comment: Category
      type: manyToOne
  values:
    Valeur1: {  Code: AME_BOARD_CONSULT, Label: Recherche des demandes d'agrément AME }
    Valeur2: {  Code: AME_AGR_CONSULT, Label: Consultation des demandes d'agrément AME }
```
où RightCategory est elle-même une table de référence statique.

Actuellement, on ne peut pas indiquer de valeur pour RightCategory dans les values.
Mais même sans la préciser, la génération plante : 
![image](https://user-images.githubusercontent.com/9590375/192981313-e83c1cd2-78c3-4433-bd4c-ca4f9d3f9ee3.png)

**Comment by Jerom138** [comment]
Pour info :
```
class:
  name: RightCategory
  comment: Table RightCategory
  reference: true
  decorators:
    - Builder
  properties:
    - name: Code
      comment: Code
      domain: DO_LIBELLE_LONG
      label: Code
      primaryKey: true
    - name: Label
      comment: Label
      domain: DO_LIBELLE_LONG
      label: Label
      required: true
    - name: Ordre
      comment: Ordre
      domain: DO_QUANTITE
      label: Ordre
      required: true
  values:
    Valeur1: {  Code: AME_GEST, Label: Gestion AME, Ordre: 1 }
    Valeur2: {  Code: AEMC_GEST, Label: Gestion AeMC, Ordre: 2 }
    Valeur3: {  Code: ADM_SUP, Label: Administration et Support, Ordre: 3 }
    Valeur4: {  Code: PIL_BOARD, Label: Tableau de bord et Pilotage, Ordre: 4 }
    Valeur5: {  Code: PN_GEST, Label: Gestion PN, Ordre: 5 }
```
