### ISSUE TITLE
Core : Donner la possibilité de templater les domaines et les décorateurs

### ISSUE THREAD

**Issue by gideruette** [klee-contrib/topmodel#164]
Templater les domaines et les décorateurs avec des informations des regularProperties.
Ex :

```yaml
domain:
  name: DO_ENUM_REF
  label: Type enum template
  java:
    type: "{name:pascal}"
    annotations:
      - "@Column(\"{trigram}_CODE\")"
    imports:
      - topmodel.sample.{name:pascal}
  sqlType: varchar
  ts:
    type: "{name:snake}"
    import: "@/references"
```
