### ISSUE TITLE
Core : Pouvoir créer des convertisseurs de domaines

### ISSUE THREAD

**Issue by gideruette** [klee-contrib/topmodel#181]
Pour relâcher la contrainte de 'deux propriétés doivent avoir le même domaine pour être mappées"
Le `from` représente la liste des domaines qui peuvent être convertis individuellement dans un des domaines présent dans la liste `to`.
Cela pourrait ressembler à 
```yaml
converter:
  from: 
    - DO_MONTANT
    - DO_DECIMAL
    - DO_COEFFICIENT
  to: 
    - DO_MONTANT
    - DO_DECIMAL
    - DO_COEFFICIENT
---
converter:
  from: 
    - DO_ENTIER
    - DO_DECIMAL
  to: 
    - DO_LIBELLE
  csharp:
     text: "{value}.toString()"
---
converter:
  from:
    - DO_LIBELLE
  to:
    - DO_ENTIER
    - DO_DECIMAL
  csharp:
    text: "{to.type}.Parse({value})"
---
converter:
  from: 
    - DO_LIBELLE_LONG
  to: 
    - DO_LIBELLE_COURT
    - DO_LIBELLE
  csharp:
    text: "{value}?.Substring(0, Math.Min({value}.Length, {to.length}))"
```

Dans le futur, il pourrait être intéressant de définir des mapping 1 -> n ou n -> 1
