### ISSUE TITLE
[Core] Classes abstraites et propriétés readonly

### ISSUE THREAD

**Issue by gideruette** [klee-contrib/topmodel#188]
- Ajouter l'attribut `abstract: true | false` sur les classes
- Ajouter l'attribut `readonly: true | false` sur les propriétés

Les générateurs Java / C# doivent générer des interfaces à la place des classes pour les classes marquées `abstract`.
Les interfaces contiennent un getter par propriété, et un unique setter pour toutes les propriétés non `readonly` de la classe (appelé `hydrate` ou `Hydrate`)

Les propriétés `readonly` ne seront pas settées par les mapper (y compris pour les classes non abstraites)

Ne pas générer de `hydrate` vide.

**Comment by JabX** [comment]
Avec l'exemple suivant :
```yaml
---
class:
  name: Test
  comment: Test
  abstract: true
  properties:
    - name: Id
      domain: DO_ID
      required: true
      comment: Id
    - name: Libelle
      domain: DO_LIBELLE
      readonly: true
      comment: Libelle
  mappers:
    from:
      - params:
          - class: TestDto
    to:
      - class: TestDto
---
class:
  name: TestDto
  comment: TestDto
  properties:
    - alias:
        class: Test
      readonly: false
  mappers:
    from:
      - params:
          - class: Test
    to:
      - class: Test
 ```

le mieux qu'on puisse faire avec des fonctionnalités de langage "normales" c'est quelque chose comme :
```cs
// Interface générée
interface ITest
{
    int Id { get; }

    string Libelle { get; }

    void Hydrate(int id);
}

// Mappers générés
static class Mappers
{
    static Test FromMapper(TestDto testDto)
    {
        var test = new Test();
        test.Hydrate(id: testDto.Id);
        return test;
    }

    static TestDto FromMapper(Test test)
    {
        return new TestDto { Id = test.Id, Libelle = test.Libelle };
    }

    static TestDto ToMapper(Test test, TestDto testDto = null)
    {
        testDto ??= new TestDto();
        testDto.Id = test.Id;
        testDto.Libelle = test.Libelle;
        return testDto;
    }

    // Le mapper To vers la classe abstraite ne permet pas de passer une instance pré-existante et de modifier ses champs.
    static Test ToMapper(TestDto testDto)
    {
        var test = new Test();
        test.Hydrate(id: testDto.Id);
        return test;
    }
}

// Implémentation de ITest exemple
class Test : ITest
{
    public int Id { get; private set; }

    public string Libelle { get; private set; }

    public void Hydrate(int id)
    {
        Id = id;
        Libelle = "yolo";
    }
}
```

Ce qui n'est pas très satisfaisant parce que : 
- Il faut nécessairement un constructeur public sans paramètre sur l'implémentation, ce qui veut dire qu'on n'est pas "obligé" d'appeler `Hydrate(id)` pour initialiser l'objet
- Les mappers référencent l'implémentation (`Test` tout court), ce qui va générer du "code qui ne compile pas" et qui force aussi à mettre l'implémentation dans le même package/namespace que l'interface. Je suis pas sûr que ça soit super gênant en vrai...

Il n'y a pas l'air d'avoir de solution en Java pour ne pas devoir faire ça, donc peut être que _la meilleure solution serait de tout simplement pas générer/interdire des mappers qui essaient de construire une classe abstraite en Java_.

Par contre, en C# (très) récent (preview sur .NET 6, stable en .NET 7 donc genre depuis novembre), on peut définir des méthodes statiques abstraites sur les interfaces qui, combinées avec les types génériques au runtime de .NET, offrent une réponse satisfaisante aux deux problèmes vu que je peux faire : 

```cs
// Interface générée
interface ITest
{
    int Id { get; }

    string Libelle { get; }

    static abstract ITest Create(int id);
}

// Mappers générés
static class Mappers
{
    static T FromMapper<T>(TestDto testDto)
         where T : ITest
    {
        return (T)T.Create(id: testDto.Id);
    }

    static TestDto FromMapper(ITest test)
    {
        return new TestDto { Id = test.Id, Libelle = test.Libelle };
    }

    static TestDto ToMapper(ITest test, TestDto testDto = null)
    {
        testDto ??= new TestDto();
        testDto.Id = test.Id;
        testDto.Libelle = test.Libelle;
        return testDto;
    }

    // Le mapper To vers la classe abstraite ne permet pas de passer une instance pré-existante et de modifier ses champs.
    static T ToMapper<T>(TestDto testDto)
          where T : ITest
    {
        return (T)T.Create(id: testDto.Id);
    }
}

// Implémentation de ITest exemple
class Test : ITest
{
    private Test()
    {
    }

    public int Id { get; private init; }
    // init ça veut dire que je peux le mettre dans un initialiseur de classe mais pas après, donc c'est mieux que set
    public string Libelle { get; private init; } 

    public static ITest Create(int id)
    {
        return new Test
        {
            Id = id,
            Libelle = "yolo"
        };
    }
}
```

où j'arrive bien à avoir un constructeur privé dans ma classe et a renseigner le type de l'instance à utiliser à l'appel du mapper en générique. Il y a un recast un peu moche en `T` derrière l'appel à `Create` dans le mapper puisque la méthode renvoie l'interface, mais bon ça ne devrait jamais poser problème (à moins que l'implé renvoie une instance d'une classe différente...).

Ma PR implémente ça en C# du coup :)
