### ISSUE TITLE
Pouvoir renseigner des libellés en plusieurs langues

### ISSUE THREAD

**Issue by JabX** [klee-contrib/topmodel#19]
Par exemple :
```yaml
properties:
  - name: Label
    label:
      en: Label
      fr: Label
    domain: DO_LABEL
    comment: Un libellé
```
Doit pouvoir coexister avec l'existant (juste un string).
Le générateur de ressources devra générer un fichier json/js par langue
