### ISSUE TITLE
Déclaration d'une colonne déclenche l'ajout de l'annotation @NotNull

### ISSUE THREAD

**Issue by kbuntrock** [klee-contrib/topmodel#198]
La déclaration d'une colonne (nullable ou non, pas de différence) va déclencher l'apparition de l'annotation @NotNull sur un champs d'entity. Cette annotation de devrait tout simplement pas être présente.

Voir exemple de déclaration de domain ci-dessous : 

```
domain:
  name: PROFIL
  label: profil
  java:
    type: Profil
    imports:
      - com.kleegroup.cg.api.enumeration.Profil
    annotations:
      - target: Persisted
        imports:
          - "jakarta.persistence.Convert"
          - "com.kleegroup.cg.persistence.entity.converter.ProfilConverter"
        text: "Convert(converter = ProfilConverter.class)"
      - target: Persisted
        imports:
          - "jakarta.persistence.Column"
        text: 'Column(name = "pro_id", nullable = false)'
  sqlType: bigint
```
