### ISSUE TITLE
[Core] Possibilité de rajouter des propriétés calculées

### ISSUE THREAD

**Issue by gideruette** [klee-contrib/topmodel#264]
Sur une propriété, cela pourrait prendre la forme : 

```yaml
computed: {proprieteA} + {proprieteB}
```
ou bien :
```yaml
computed: 
  java: {proprieteA} + " " + {proprieteB}
  ts:  `${{proprieteA}} + " " + {{proprieteB}}`
```
