### ISSUE TITLE
 [Core] Amélioration de la gestion des valeurs (values et defaultValues)

### ISSUE THREAD

**Issue by gideruette** [klee-contrib/topmodel#293]
Rationnaliser la gestion des valeurs ex : 
```yaml
values: 
  USR: { Date: now, Profile: ADM}

DATE
  java:
    valueTemplate: new LocalDate("{value}")
    values:
      now: 
        text: LocaleDate.now()
        imports: [java.utils.LocaleDate]
      tomorrow: LocaleDate.now().plus(1, 'day')
```
