### ISSUE TITLE
[Core] Ajouter des annotations de propriétés dans les décorateurs

### ISSUE THREAD

**Issue by gideruette** [klee-contrib/topmodel#308]
L'idée est de pouvoir référencer des propriétés par leur nom, et d'y ajouter des annotations
ex : 
```yaml
    propertyAnnotations:
        - text: CreationDate
          target: dateCreation
```

Text supporte le templating de la propriété ciblée
Target supporte le templating de la classe ou du endpoint

Les deux supportent les paramètres, ce qui permettrait de faire 
Target doit résoudre sur un nom de propriété dans une classe, et sur un paramName dans un endpoint

```yaml
    propertyAnnotations:
        - text: P("{$1}")
          target: "{$1}"
```
