### ISSUE TITLE
Import de la librairie dans les classes qui ne l'utilisent pas 

### ISSUE THREAD

**Issue by tthery** [klee-contrib/topmodel#325]
J'ai ajouté un domain qui utilise une annotation : 
![image](https://github.com/klee-contrib/topmodel/assets/122804190/4c1b8b9e-449b-4388-96e0-1536ac30dcad)

L'imports de cette librairie est effectué dans toutes les classes qui utilisent l'objet qui a ce domaine comme propriété en plus de l'objet lui-même.

Non bloquant mais ajout d'imports non utilisés.

**Comment by JabX** [comment]
Salut,

Ajoute 2 indentations devant ton `imports` pour rattacher tes imports à l'annotation et non au type du domaine, et ça devrait résoudre ton problème :)

```yaml
java:
  type: Long
  annotations:
    - text: EqualsAndHashCode.Include
      imports:
        - lombok.EqualsAndHashCode
```
