### ISSUE TITLE
[JPA] Les imports d'un domaine ne sont pas reportés dans les repositories

### ISSUE THREAD

**Issue by etienne582** [klee-contrib/topmodel#358]
Je créer un domain UUID avec un import java.util

```
domain:
  name: DO_UUID
  label: UUID
  ts:
    type: string
  java:
    type: UUID
    imports:
      - java.util.UUID
  sql:
    type: uuid
```

Je créer un classe avec un UUID en PK

```
class:
  name: User
  trigram: USR
  comment: Utilisateurs de l'application
  properties:
    - name: id
      primaryKey: true
      domain: DO_UUID
      comment: Object Id de l'utilisateur sur l'azure ad
```

L'import java.util.UUID n'est pas généré dans le repository UserDao
