### ISSUE TITLE
[Core] Donner la possibilité d'ajouter des paramètres nommés aux décorateurs ou domaines

### ISSUE THREAD

**Issue by gideruette** [klee-contrib/topmodel#372]
Actuellement il est possible de donner aux décorateurs et aux domaines des valeurs à utiliser dans les templates.
Ces valeurs sont données dans un tableau, l'idée de cette évolution est de donner la possibilité de donner un objet (en laissant l'option tableau disponible).

Exemples :

```yaml
domain:
  name: DO_CODE
  csharp:
    annotations:
      - text: MyAnnotation(Param1 = "{$Param1}", Param2 = "{$Param2}"))
```

```yaml
properties:
  - name: MyProperty
    domain:
      name: CODE
      parameters:
        Param1: Value1
        Param2: Value2
```

Et pour les décorateurs

```yaml
decorator:
  name: hasRoleAndPerimeter
  description: A au moins un des droits nécessaires pour pouvoir accéder au endpoint
  java:
    annotations:
      - "@HasRoleAndPerimeter(role ={$role}, perimeter = {$perimeter})"
    imports:
      - org.springframework.security.access.prepost.PreAuthorize
```

```yaml
  decorators:
    - hasRoleAndPerimeter:
        role: ADM
        perimeter: NAT
```

**Comment by gideruette** [comment]
Offrir la possibilité de définir la signature des paramètres des domaines et décorateurs : 
```yaml
parameters:
  - name: param1 
    comment: description obligatoire du paramètre 1
    default: titi
  - name: param2
    comment: description obligatoire du paramètre 2
```

Ce qui permettrait de rendre plus explicite l'utilisation des paramètres nommés, de valider les templates ainsi que le références aux domains/decorateurs qui les utilisent
