### ISSUE TITLE
[SQL] Resource générée en double lorsque l'on utilise des alias de champs dans les entity

### ISSUE THREAD

**Issue by dchallas** [klee-contrib/topmodel#394]
### Attendu :

Ne pas générer les resources pour les alias des entities car déjà généré par l'objet d'origine

### Constat :

Lorsque j'ai le même alias de champ entre plusieurs entities distinctes j'ai des doublons dans le fichier de resourceFile

```
 procedural:...
      resourceFile: V000.106__referentiel_resources.sql
```

```
class:
  name: Note
  reference: true
  properties:
    - name: Code
      label: Code
      primaryKey: true
      domain: DO_CODE
      comment:  Code
 class:
  name: Precision
  reference: true
  properties:
  - alias:
       class: Note
       include: Code
      prefix: true
      required: false
```
        
Dans mon cas j'ai trois fois le même insert : un pour l'objet d'origine et un par alias utilisé
```
/**    Initialisation des traductions des propriétés de la table Note    **/
INSERT INTO I18N_RESSOURCE_LIBELLE(RESOURCE_KEY, LOCALE, LABEL)VALUES ('note.code', 'fr_FR', 'Code');
/**    Initialisation des traductions des propriétés de la table Precision    **/
INSERT INTO I18N_RESSOURCE_LIBELLE(RESOURCE_KEY, LOCALE, LABEL)VALUES ('note.code', 'fr_FR', 'Code');
```

Merci d'avance
