### ISSUE TITLE
Soucis prise en compte `outputDirectory` pour tmdgen

### ISSUE THREAD

**Issue by DricomDragon** [klee-contrib/topmodel#415]
Bonjour,

J'ai un projet qui utilise `modgen` et `tmdgen`. Quand je configure `outputDirectory` pour ce dernier, il n'est pas pris en compte dans le chemin des fichiers créés, alors qu'il est pris en compte dans les lignes écrites dans `tmdgen.lock`.

Comportement constaté : les fichiers `.tmd` sont générés dans le dossier `/model/MyApp/`.

Comportement attendu : les fichiers `tmd` généres par `tmdgen` sont générés dans le dossier spécifé par `outputDirectory`.

Structure de mon dossier `model` : 

- _meta/
  - domains.tmd
- bounds/
  - bound-1/
    - bound-1-open-api.yml
  - tmdgen.config
- business/
  - domain-a/
  - domain-b/
    - 01_refs.tmd
    - 02_entities.tmd
    - 03_dtos.tmd
    - 04_api.tmd
- tmdgen.lock
- topmodel.config
- topmodel.lock

  
![Capture_outputDirectory_pas_respecte_filtre](https://github.com/user-attachments/assets/119f0258-a574-415f-85f0-b3d019d11184)

![Capture_outputDirectory_pas_autorise_filtre](https://github.com/user-attachments/assets/5c1f2273-da40-4ca3-9409-5ecc5176a083)

tmdgen.confg : 

```yaml
modelRoot: '../../model'
openApi:
  - module: MyApp
    outputDirectory: './bounds/bound-1'
    domains:
      - type: list
        domain: DO_LIST
    source: ./sig/bound-1-open-api.yml
    modelTags:
      - bound-1
    endpointTags:
      - bound-1
```
