### ISSUE TITLE
Config javascript `entityTypesPath` ne créée pas des imports relatifs

### ISSUE THREAD

**Issue by DricomDragon** [klee-contrib/topmodel#426]
Habituellement, préfixer l'import avec `./` permet de faire des imports relatifs, mais cela semble ne pas fonctionner avec la config `entityTypesPath` du javascript.

Version TopModel : 2.3.2
Version générateur JS : 1.1.3

Extrait de `Topmodel.config` :

```yaml
javascript:
  - tags:
      - front
    domainPath: "./domain-defs"
    entityTypesPath: "./stores/entity"
```

Imports du modèle généré : 

```yaml
import {EntityToType, FieldEntry2} from "./stores/entity";
import {LIBELLE_100} from "../../domain-defs";
```

Attendu : 

```yaml
import {EntityToType, FieldEntry2} from "../../stores/entity";
import {LIBELLE_100} from "../../domain-defs";
```
