### ISSUE TITLE
[Core] Donner la possibilité de débrayer la génération pour certains fichiers

### ISSUE THREAD

**Issue by gideruette** [klee-contrib/topmodel#431]
Afin de ne pas bloquer les projets en attente d'un fix, d'une évolution ou autre, dans la config, donner la possibilité d'ajouter une liste de fichiers à ignorer avec un commentaire : 
```yaml
ignoreFiles:
  - path: [Chemin du fichier à ignorer]
    comment: [Raison du débraillage]
```

Avec un warning (ignorable comme tous les warnings) qui averti que le fichier a été ignoré, en ajoutant la raison.

Si le fichier n'est plus généré, modgen doit bien le supprimer
Si le fichier le fichier référencé n'est pas censé être généré par modgen, un autre warning est affiché
