### ISSUE TITLE
[JS] : Permettre l'ajout d'un HttpOption lors de la génération d'un service d'upload de fichier

### ISSUE THREAD

**Issue by Plantin7** [klee-contrib/topmodel#448]
Lors de la la génération d'un endpoint d'upload de fichier avec un domain MultipartFile, le service TS généré ne permet l'ajout d'un HttpOption : 

Fichier TMD :
```
endpoint:
  name: UploadDocument
  method: POST
  route: document/upload
  description: Upload d'un document
  params:
    - name: File
      label: File
      comment: Fichier à uploader
      domain: DO_MULTIPARFILE
      required: true
  returns:
      composition: DocumentDto
      domain: DO_RESPONSE_ENTITY
      name: documentDto
      comment: Le détail du fichier enregistré
```

Code généré :
```
   /**
     * @description Upload d'un document
     * @param file Fichier à uploader
     * @returns Le détail du fichier enregistré
     */
    uploadDocument(file: File): Observable<DocumentDto> {
        const body = new FormData();
        this.fillFormData(
            {
                file
            },
            body
        );
        return this.http.post<DocumentDto>(`/document/upload`, body);
    }
```

    private fillFormData(data: any, formData: FormData, prefix = "") {
        if (Array.isArray(data)) {
            data.forEach((item, i) => this.fillFormData(item, formData, prefix + (typeof item === "object" && !(item instanceof File) ? `[${i}]` : "")));
        } else if (typeof data === "object" && !(data instanceof File)) {
            for (const key in data) {
                this.fillFormData(data[key], formData, (prefix ? `${prefix}.` : "") + key);
            }
        } else {
            formData.append(prefix, data);
        }
    }`

Le besoin serait de permettre d'animer une progressbar d'upload et pour cela il faudrait rajouter un HttpOption au niveau du post : 

```

  ...
  const httpOptions = {
      reportProgress: true,
      observe: 'events' as const
    };
  return this.http.post<DocumentDto>(`/document/upload`, body, **httpOptions**);

```
