### ISSUE TITLE
[Core] Dans les templates, les variables contenant des morceaux d'autres variables sont mal résolues

### ISSUE THREAD

**Issue by gideruette** [klee-contrib/topmodel#469]
Si j'ai ce domain
```yaml
---
domain:
  name: RESPONSE_ENTITY
  label: Response Entity
  parameters:
    - name: ResponseType
      comment: Type de réponse souhaité
    - name: ResponseTypeImport
      comment: Import du type de réponse souhaité
  ts:
    type: any
  java:
    type: ResponseEntity<{ResponseType}>
    imports:
      - org.springframework.http.ResponseEntity
      - "{ResponseTypeImport}"
```

Alors le template `{ResponseTypeImport}` sera résolue avec la valeur donnée à "ResponseType" car cette dernière en est un préfix
