### ISSUE TITLE
Core : Ajouter une notion de décorateur de classe

### ISSUE THREAD

**Issue by gideruette** [klee-contrib/topmodel#76]
Pour gérer des genre de méta-classe (domaine de classe) pour :
- Propriétés supplémentaires
- Implémentation d'interfaces et de classes abstraites (non définies dans TopModel)

exemple de définition : 
```yaml
decorator:
  name: # Nom du décorateur
  java:
    imports: # Liste des imports à ajouter à la classe
    extends: # Classes à ajouter à la classe
    implements: # Liste des interfaces à ajouter à la classe
    annotations: # Liste des annotations à ajouter à la classe
  csharp:
    imports: # Liste des imports à ajouter à la classe
    extends: # Classes à ajouter à la classe
    implements: # Liste des interfaces à ajouter à la classe
    annotations: # Liste des annotations à ajouter à la classe
  properties: # Liste des propriétés à ajouter à la classe en tant qu'alias qui pointent vers le décorateur. Ces propriétés peuvent elles-même être des alias/associations etc...
```

Et sur la classe : 
```yaml
class:
   decorators: # Liste des décorateurs à ajouter à la classe
```
