### ISSUE TITLE
Core : modéliser le chemin d'une propriété d'alias

### ISSUE THREAD

**Issue by gideruette** [klee-contrib/topmodel#86]
Ceci pourrait ressembler à :

```yaml
alias:
        class: Utilisateur
        from: 
          class: Declaration
          join: UtilisateurIdDeclarant
          from: 
            class: Entreprise
            join: DeclarationId
        include: Nom
```
